[settings]
experimental = true

[tools]
"aqua:nextest-rs/nextest/cargo-nextest" = "latest"
"cargo:cargo-sort" = "latest"
rust = { version = "latest", profile = "default", components = "llvm-tools,rust-analyzer" }
"ubi:cargo-bins/cargo-binstall" = "latest"
"cargo:cargo-release" = "latest"
node = "22"
bun = "latest"
pkl = "latest"
